# Generated by Django 4.0.4 on 2022-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=0),
        ),
    ]
